services:
  django_admin:
    build: .
    pull_policy: build
    restart: always
    cpus: '1.0'
    ports:
      - "8081:8000"
    networks:
      django_network:
    environment:
      POSTGRES_HOST: psql_db
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    volumes:
      - static:/app/staticfiles
      - ./media:/app/media
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             gunicorn -w 1 project.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static:
    external: true
  media:
    external: true


networks:
  django_network:
    name: local_network
    external: true
